version: '2'
services:
  app:
    container_name: app
    build:
      context: ../../../..
      dockerfile: ./docker/src/main/docker/Dockerfile
    networks:
      - net
    ports:
      - 80:8080
networks:
  net:
    driver: bridge

